### ISSUE TITLE
screen resolution for tablets??

### ISSUE THREAD

**Issue by chrisrabe** [JC626/MathForKIds#2]
Will we aim for tablet compatibility? Or do you want me to disable compatibility with tablet sized resolution??

**Comment by JC626** [comment]
Hmmm.... ideally would want it to be tablet compatible. Maybe we should do it in a later update

**Comment by chrisrabe** [comment]
Tablet compatibility is extremely tricky because it means we have to reformat everything :'(

**Comment by MeganLiang** [comment]
Nah, we used dp which formats the images and buttons to fit the screen

**Comment by dean012** [comment]
Not sure if it's my phone problem but sometimes the app crash when switching to other application

**Comment by chrisrabe** [comment]
what do you mean by that? Do you mean that if you close the app, it crashes? Also, using dp feels like hardcoding it. I did the screen size by using layout_weight and weights because apparently the elements resizes itself based on the percentage of the screen

**Comment by JC626** [comment]
Ah good idea using the weights.

**Comment by dean012** [comment]
do you want the cat to be bigger than the speech bubble? or the other way round?

**Comment by chrisrabe** [comment]
Is cat meant to be bigger than speech bubble?

**Comment by dean012** [comment]
Janice deleted my comment -_-

**Comment by chrisrabe** [comment]
I think that someone tested this game on tablet and said it was fine? So I might as well close this issue
