### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by chrisrabe** [JC626/MathForKIds#4]
- set screen orientation to portrait in all screens
- implement reset button in settings
- can't enter when no input -- skip questions button?
- whole number answers for dividing
- change to relative layout for question screen
- hints (????) <last priority>
- find a way to reduce number of steps taken by algorithm [difficult]

**Comment by JC626** [comment]
Screen orientation done
Division whole number answers done
Relative layout doesn't help.... don't know how to fix yet

**Comment by dean012** [comment]
Do you guys want reset button for each thing like reset button for high score, achievement etc or 1 button that does everything

**Comment by JC626** [comment]
Does everything. I was looking into clearing the system cache but this is too complex
