### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by JC626** [JC626/MathForKIds#6]
I was just wondering.

Should we put an About page into the application to say this:

> Creators
> 
> ```
> Dean Ong
> Chris Rabe
> Janice Chin
> Megan Liang
> ```
> 
> This is an android mobile game application which was created for the Summer of Tech 2016 android hackathon event.

Or should we put it in the description of the application on the Google Play store listing?

**Comment by chrisrabe** [comment]
I've created a README.md file in the github page. I think you should just post that instead. Markdown language only exist in github so you might wanna change the formatting when putting it in the about page.

> # MathForKids
> 
> ### Creators
> - Dean Ong
> - Chris Rabe
> - Janice Chin
> - Megan Liang
> 
> ### Why this was made:
> 
> This is an android mobile game application which was created for the Summer of Tech 2016 android hackathon event.
> 
> ### Aim
> 
> The game's purpose is to allow kids to apply and sharpen their skills in solving mathematics problems in a fun and engaging manner.
> It covers various of basic arithmetic questions, which includes addition, subtraction, multiplication and division.
> 
> ### Reward System
> 
> Our game offers achievements and highscores so that kids can show off their skills to their friends and families.

Technical Details about the program should be left out because majority of the users would not need to know about the algorithm implemented in this system

**Comment by JC626** [comment]
I have put your readme file into the description of the store listing. 
However, I have excluded author names.
This is because I want everyone's opinion whether they wish to share their names due to privacy concerns.

There are three options:

1) Put our names in the Google play store for EVERYONE to see
2) Put our names only inside the application (in an About page)
3) Omit their name (if you wish)

I would preferably choose option 2 but don't mind any option.

**Comment by chrisrabe** [comment]
Option 2 is good

**Comment by dean012** [comment]
option 2

**Comment by MeganLiang** [comment]
option 2 as well :)

**Comment by JC626** [comment]
I will implement the About page soon and then will definitely release the application on the Google Play store!
